apiVersion: apps/v1
kind: Deployment
metadata:
  name: sijoittaja-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sijoittaja-backend
  template:
    metadata:
      labels:
        app: sijoittaja-backend
    spec:
      containers:
        - name: sijoittaja-backend
          image: l0uko/sijoittaja-backend:kokeilu3
          ports:
            - containerPort: 3443
          volumeMounts:
          - name: backend-certs
            mountPath: /etc/tls/private
            readOnly: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      volumes:
      - name: backend-certs
        secret:
          secretName: backend-tls
