# How to run this deployment:
#  Run 
apiVersion: apps/v1
kind: Deployment #type of the thing, deployment or service. Service helps with networking
metadata:
  name: sijoittaja-dep
spec:
  replicas: 1 #amount of copies of the image
  selector:
    matchLabels:
      app: sijoittaja
  template:
    metadata:
      labels:
        app: sijoittaja
    spec:
      containers: #here is the used docker image
        - name: sijoittaja
          image: l0uko/sijoittaja-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6443
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
