#currently copied from materials, placeholder values

#apiVersion: v1
#kind: Service
#metadata:
#  name: sijoittaja-np
#spec:
#  type: NodePort
#  selector:
#    app: sijoittaja
#  ports:
#    - name: http
#      nodePort: 35107
#      protocol: TCP
#      port: 3000
#      targetPort: 4173
