apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sijoittaja-route
  namespace: toska-playground
  labels:
    app: sijoittaja
    type: external
spec:
  host: demoapp-toska-playground.ext.ocp-test-0.k8s.it.helsinki.fi 
  port:
    targetPort: 3000 
  to:
    kind: Service
    name: sijoittaja-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None