#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: sijoittaja-backend-route
#  namespace: ohtuprojekti-staging
#  labels:
#    app: sijoittaja-backend
#    type: external
#spec:
#  host: ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi
#  port:
#    targetPort: 3000
#  to:
#    kind: Service
#    name: sijoittaja-backend-svc
#  tls:
#    termination: edge
#    insecureEdgeTerminationPolicy: Redirect
#  wildcardPolicy: None