apiVersion: v1
kind: Service
metadata:
  name: sijoittaja-backend-svc
spec:
  selector:
    app: sijoittaja-backend
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 3000
  type: ClusterIP